[package]
name = "monkey-lang"
version = "0.1.0"
authors = ["Ray Tran <ray@artran.co.uk>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
rstest = "0.18.2"
speculoos = "0.11.0"
